[package]
name = "tadpole_ffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "_tadpole_ffi"
crate-type = ["cdylib"]

[dependencies]
tadpole = { git = "https://codeberg.org/zhuriel/tadpole.git", version = "1.0"}
tadpole_frontend = { git = "https://codeberg.org/zhuriel/tadpole.git", version = "1.0"}
nom = "8.0.0"
